[programs.localnet]
solana_twitter = "2H8eiMJyS8TAQSBxk1ZqVNwc23vqGmdDvnq4Y4U8es3Z"

[programs.devnet]
solana_twitter = "2H8eiMJyS8TAQSBxk1ZqVNwc23vqGmdDvnq4Y4U8es3Z"

[programs.mainnet]
solana_twitter = "2H8eiMJyS8TAQSBxk1ZqVNwc23vqGmdDvnq4Y4U8es3Z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/tian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
